"""Add an auditing table.

Revision ID: 4a1138490008
Revises: 11370957da30
Create Date: 2022-06-12 17:32:36.488178

"""
import datetime

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4a1138490008'
down_revision = '11370957da30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditing',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), default=datetime.datetime.now, nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))

    op.create_index(op.f('ix_auditing_created_date'), 'auditing', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditing_created_date'), table_name='auditing')
    op.drop_table('auditing')
    # ### end Alembic commands ###
